### ISSUE TITLE
Servidor

### ISSUE THREAD

**Issue by inacionery** [simpleanduseful/clockin#11]
Disponibilizar um servidor da Liferay para podemos utilizamos como ambiente de produção.

**Comment by inacionery** [comment]
Já foi solicitado a 'Papel' o servidor

**Comment by gallindo** [comment]
@inacionery ,

**Perguntas:**
1. Ele deu algum prazo ?
2. Disse se vai ser local ou na nuvem ?

**Comment by inacionery** [comment]
@gallindo,

Não. Segunda irei cobrar novamente.

Ele não falou, mas acredito que seja local.

**Comment by inacionery** [comment]
done!
