### ISSUE TITLE
Erro no Javascript ao tentar efetuar login utilizando o Mozilla Firefox

### ISSUE THREAD

**Issue by walber** [simpleanduseful/clockin#8]
Não foi possível efetuar login utilizando o navegado Mozilla Firefox 43.0.4. Ao tentar efetuar login, ocorre o seguinte erro no console.
![screenshot from 2016-01-25 20-16-43](https://cloud.githubusercontent.com/assets/4422978/12566405/93705f06-c3a0-11e5-9083-e91b89f57384.png)

**Comment by clovisdasilvaneto** [comment]
tu rodou o bower install e o npm install?

**Comment by walber** [comment]
Eu executei estes comandos, mas não obtive sucesso. Quando eu entro com o Google Chrome 47.0, funciona corretamente.

**Comment by clovisdasilvaneto** [comment]
Beleza. Vou dar uma olhada

**Comment by clovisdasilvaneto** [comment]
Valeeu :D

**Comment by inacionery** [comment]
done!
